version: 2

project_name: todoist

before:
  hooks:
    - go mod tidy

builds:
  - id: todoist
    main: ./cmd/todoist
    binary: todoist
    ldflags:
      - -s -w
      - -X github.com/mattjefferson/todoist-cli/internal/app.version={{.Version}}
      - -X github.com/mattjefferson/todoist-cli/internal/app.commit={{.Commit}}
      - -X github.com/mattjefferson/todoist-cli/internal/app.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

release:
  name_template: "{{ .ProjectName }} {{ .Version }}"
  prerelease: auto

changelog:
  disable: true
